version : "3"

services:

  jenkins:
     image: jenkins/jenkins:jdk11
     ports:
      - "8880:8080"
      - "50000:50000"
     volumes:
      - ../volumes/jenkins:/var/jenkins_home
     networks:
      - docker_network
    
  ubuntu-jenkins-slave:
      build: 
       context: ../dockerfiles/slave
      command : 
       - ls
      container_name: ubuntu-jenkins-slave
      networks:
       - docker_network
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
      command: java -jar agent.jar -jnlpUrl http://192.168.44.44:8880/computer/Node_1/jenkins-agent.jnlp -secret 6c1ecd3f4932d6d545b4640718297c045cf44a875dbbf662072abe1f5d136b77 -workDir "/home/"
      depends_on:
       - jenkins
      
  artifactory:
      image: docker.bintray.io/jfrog/artifactory-oss
      networks:
       - docker_network
      container_name: artifactory
      volumes:
       - ../volumes/artifactory:/var/opt/jfrog/artifactory
      ports:
       - "8081:8081"
       - "8082:8082"
      
  selenium_hub:
      image: selenium/hub
      container_name: selenium_hub
      ports:
       - "4444:4444"
      networks:
       - docker_network

  selenium_firefox:
      image: selenium/node-firefox
      networks:
       - docker_network
      environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
      depends_on: 
      - selenium_hub
      
networks:
 docker_network:
  driver: bridge